subject: 'cat:cs.*'

# 検索キーワード
keywords:
        agriculture: 7
        agritech: 7
        green house: 8
        environment sensors: 5
        remote sensing: 5
        database: 3
        machine learning: 3


# 出力する論文数
num_papers: 100

# 何日前まで遡るか（例：go_back_date=365で直近1年分の検索）
go_back_date: 365
