subject: 'cat:cs.*'

# 検索キーワード
keywords:
        carbon footprint: 8
        scope3: 8
        co2 emission: 8
        secure computation: 2
        homomorphic encryption: 1
        database: 3


# 出力する論文数
num_papers: 100

# 何日前まで遡るか（例：go_back_date=365で直近1年分の検索）
go_back_date: 365
